[phases.setup]
nixPkgs = ['...', 'php82', 'php82Packages.composer']

[phases.build]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'php-fpm -y /assets/php-fpm.conf & nginx -c /assets/nginx.conf'