services:
  - type: web
    name: twins-elegance-api
    env: php
    buildCommand: composer install --optimize-autoloader --no-dev
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: twins-elegance-db
          property: connectionString

databases:
  - name: twins-elegance-db
    databaseName: twins_elegance
    user: twins_user